#!/usr/local/bin/node

const help = require("./help.js");
const test = require("./test.js");
const Puller = require("./pull.js");
const Stats = require("./stats");
const { stat } = require("fs");
const Pusher = require("./push.js");

args = process.argv;

if ( args.length <= 2 || args[2] == "help" ) {

    help();

} else {

    switch(args[2]) {
        case "test":
            test();
            break;

        case "stats":
            const stats = new Stats();
            stats.get_operation_types().then(() => {
                if ( args.length == 4 ) {
                    if ( args[3] == "-mr") {
                        stats.sort_by_most_recent();
                        stats.display(10);
                    } else if ( args[3] == "-md") {
                        stats.sort_by_most_done();
                        stats.display(10);
                    } else {
                        console.log("Unknown option to stats")
                    }
                } else {
                    stats.display_all();
                }
            });
            break;

        case "pull":
            let puller = new Puller("staging");
            puller.pull()
                  .catch(error => {
                      console.log(error)
                  });
            break;

        case "push":
            let pusher = new Pusher();
            pusher.push()
                  .catch(error => {
                      console.log(error)
                  });
            break;

        default:
            console.log("unknown command '" + args[2] + "'. Try 'crush help'");
    }

}