#!/usr/local/bin/node

const help = require("./help.js");
const test = require("./test.js");
const stats = require("./stats.js");

args = process.argv;

if ( args.length <= 2 || args[2] == "help" ) {

  help();

} else if ( args.length == 3 ) {

    switch(args[2]) {

        case "test":
            test();
            break;

        case "stats":
            stats.stats();
            break;

        default:
            console.log("unknown command '" + args[2] + "'. Try 'crush help'");

    }

} else {
    switch(args[3]) {
        case "-mr":
            stats.most_recent();
            break;

        case "-md":
            stats.most_done();
            break;

        default:
            console.log("unknown option '" + args[3] + "' for command '" + args[2] + "'. Try 'crush help'");

    }
}
